### PR TITLE
address sparse hessian update

### PR DESCRIPTION
**Pull request by slwu89**
This addresses #10. I also updated Project.toml to restrict to versions after your PR (https://github.com/JuliaDiff/SparseDiffTools.jl/pull/190). Happy for comments!

### CODE REVIEW

**Comment by slwu89** [comment]
Hey @ElOceanografo! Just wanted to see if you were still interested in this.

**Comment by slwu89** [comment]
ping @ElOceanografo

**Comment by ElOceanografo** [comment]
Thanks for the PR, and sincere apologies for taking so long on this--you happened to submit it when I was on parental leave last year and it got by me. 

FYI, I am still interested in this repo, and have been working on some other improvements (in a local branch that almost got lost when my laptop died...but that's another story). Will hopefully be merging them in soon.

**Comment by slwu89** [comment]
Thanks! I'm glad it's useful, I'm looking forward to checking out those new features.

**Pull request merged**
