### PR TITLE
Avoid collecting `v`

### PR DESCRIPTION
**Pull request by gdalle**
Here's a proposal fixing https://github.com/gdalle/DifferentiationInterface.jl/issues/594#issuecomment-2430989350

You probably want to add test cases with ComponentArrays to your test suite

### CODE REVIEW

**Comment by ElOceanografo** [comment]
Thanks for the quick PR! Glad the `collect`ing was an easy fix, I added it recently to work around some `ComponentArray`-related bug that I must have fixed another way.

**Comment by ElOceanografo** [comment]
I currently have it as a direct dependency, since I need to dispatch on `ComponentArray` for an index-handling function [here](https://github.com/ElOceanografo/MarginalLogDensities.jl/blob/de132ed9023af800a8d9f1341c77e376372cc439/src/MarginalLogDensities.jl#L192).

**Comment by gdalle** [comment]
Sure but do you run some of your tests on ComponentYrrays ?

**Comment by ElOceanografo** [comment]
Planning to add more, but yes, I've got basic ones e.g. [here](https://github.com/ElOceanografo/MarginalLogDensities.jl/blob/de132ed9023af800a8d9f1341c77e376372cc439/test/runtests.jl#L61) and [here](https://github.com/ElOceanografo/MarginalLogDensities.jl/blob/de132ed9023af800a8d9f1341c77e376372cc439/test/runtests.jl#L111). That's how I caught this issue ;)

**Pull request merged**
