### PR TITLE
Transition to DI v0.6

### LINKED ISSUE #30: Use DifferentiationInterface v0.6
The [new release of DI](https://github.com/gdalle/DifferentiationInterface.jl/releases/tag/DifferentiationInterface-v0.6.0) introdcuced a few breaking changes, as well as some new features that could be useful for this package.

### PR DESCRIPTION
**Pull request by gdalle**
@ElOceanografo the tests don't pass yet but this should be enough to get you started.

Fixes #30 

Supersedes #27, #28, #29

---

**Versions**

- Bump Julia compat to 1.10

**Source code**

- Upgrade compat bounds of DI, Optimization and OptimizationOptimJL
- Add SparseMatrixColorings as a dep since the sparse functionality is now in a DI extension
- Change the order of arguments to put the `prep` (new name for `extras`) before the backend
- Use the new `Constant` wrapper for non-differentiated arguments
- Avoid constraining the type of `prep` since it is not part of DI's public API

> [!WARNING]
> The new `Constant` wrapper is not efficient for ReverseDiff because one can no longer compile a tape that is constant-independent, so preparation becomes useless. So if some of your workflows were using ReverseDiff you may see a big slowdown.

### CODE REVIEW

**Comment by gdalle** [comment]
Very strange that the tests pass on nightly but fail on 1.10

**Comment by ElOceanografo** [comment]
Thanks for the quick PR! I had just started on an almost verbatim one when I got the notification. 

The test failure is odd, and seems a bit intermittent when I run it locally. Relaxing the `atol=0.01` to `atol=0.1` consistently makes the test pass...maybe something to do with RNG seeding, and/or some numerical weirdness in one of the solvers?

**Comment by ElOceanografo** [comment]
e.g., see the warning about unit testing here: https://docs.julialang.org/en/v1/stdlib/Random/

**Comment by gdalle** [comment]
You may want to use StableRNGs to get version-independent streams of random numbers.

**Comment by ElOceanografo** [comment]
RNGs seemed to be the main issue. Thanks for the help!

**Pull request merged**
